### ISSUE TITLE
Release 0.11.0 checklist

### ISSUE THREAD

**Issue by suvajit-sarkar** [hyperledger/bevel#1795]
# Release Checklist

## Pre-release Test Checklist
- [x] The release checklist issue is created for the release ?
- [x] Sprints in the release are closed ?
- [x] The release change log and READMEs are updated ?
* Documentation
    - [x] The documents have been updated with release dates ?
    - [x] The rollback process is documented ?
    - [ ] The version numbers are incremented ?
* Testing
    - [ ] Smoke test scenario are create and tested ?
    - [ ] All new functionality are manually tested on a release build ?
    - [ ] CI/CD verified and working ?
- [x] All stakeholders signed off for the release
- [x] The code is merged into main

## Post-release Test Checklist
- [ ] CI/CD pipeline passed
- [ ] The new release instructions work using the released artifact?
- [ ] Read the docs reflect with updated release changes and tags
- [ ] Release communications are sent
- [ ] Close the release checklist issue
