### ISSUE TITLE
release v0.15 checklist

### ISSUE THREAD

**Issue by suvajit-sarkar** [hyperledger/bevel#2367]
# Relase Checklist

## Pre-release Test Checklist
- [x] The release checklist issue is created for the release ?
- [x] Sprints in the release are closed ?
- [x] The release changelog and READMEs are updated ?
* Documentation
    - [x] The documents have been updated with release dates ?
    - [ ] The rollback process is documented ?
    - [x] The version numbers are incremented ?
* Testing
    - [ ] Smoke test scenario are create and tested ?
    - [x] All new functionality are manually tested on a release build ?
    - [ ] CI/CD verified and working ?
- [x] All stakeholders signed off for the release
- [x] The code is mergered into main

## Post-release Test Checklist
- [ ] CI/CD pipeline passed
- [x] The new release instructions work using the released artifact?
- [ ] Read the docs reflect with updated release changes and tags
- [ ] Release communitations are sent
- [x] Close the release checklist issue

**Comment by suvajit-sarkar** [comment]
TODO: clean up the gh-pages index file containing old chart version
