### ISSUE TITLE
Release v1.0 checklist

### ISSUE THREAD

**Issue by suvajit-sarkar** [hyperledger/bevel#2456]
# Release Checklist

## Pre-release Test Checklist
- [x] The release checklist issue is created for the release ?
- [x] Sprints in the release are closed ?
- [x] The release changelog draft is ready ?
* Documentation
    - [x] The tool version are incremented ?
    - [x] Update roadmap
* Testing
    - [x] All new functionality and platforms are manually tested on a release build ?
    - [x] git actions workflow verified and working ?
- [x] All stakeholders signed off for the release
- [x] The code is merged into main

## Post-release Test Checklist
- [x] CI/CD pipeline passed
- [x] Released artifacts?
- [x] Read the docs reflect with updated release changes and tags
- [x] Release communications are sent
- [x] Close the release checklist issue
