### ISSUE TITLE
Release v1.1.0 checklist

### ISSUE THREAD

**Issue by suvajit-sarkar** [hyperledger/bevel#2566]
# Release Checklist

## Pre-release Test Checklist
- [x] The release checklist issue is created for the release ?
- [x] Sprints in the release are closed ?
- [x] The release changelog and READMEs are updated ?
* Documentation
    - [x] The documents have been updated with release dates ?
    - [x] The rollback process is documented ?
    - [x] The version numbers are incremented ?
* Testing
    - [x] Smoke test scenario are create and tested ?
    - [x] All new functionality are manually tested on a release build ?
    - [x] CI/CD verified and working ?
- [x] All stakeholders signed off for the release
- [x] The code is merge into main

## Post-release Test Checklist
- [x] Update helm chart releases
- [x] Read the docs reflect with updated release changes and tags
- [x] Release communications are sent
- [x] Close the release checklist issue
